version: "3.1"

services:
  ignite:
    build: .
    image: mattjtodd/ignite
    environment:
      - "IGNITE_SERVICE_NAME=ignite"
      - "IGNITE_SERVICE_PORT=47001"
    command: /run/secrets/ignite-config
    secrets:
      - ignite-config

secrets:
  ignite-config:
    external: true