version: "3.3"

services:
  ignite:
    build: .
    image: mattjtodd/ignite
    environment:
      - "IGNITE_SERVICE_NAME=ignite"
      - "IGNITE_SERVICE_PORT=47101"
    command: file:///ignite-config.txt
    configs:
      - source: ignite-config
        target: /ignite-config.txt
    ports:
      - 8080:8080
    deploy:
      replicas: 5

configs:
  ignite-config:
    external: true